### PR TITLE
Fixed emote, msg type and renamed function for quest 'Report to Goldshire'

### PR DESCRIPTION
**Pull request by cressidagp**
Also the emote part could be handle trought database on quest table. Im wondering if will better remove them from here.

### CODE REVIEW

**Review by dfighter1985 — APPROVED** [review]
Hi there!
The emote will not show up because of how Quest accepting works currently, but I'll merge your patch soon anyways.

**Comment by dfighter1985** [comment]
Merged it. Thanks a lot! :)

**Comment by cressidagp** [comment]
I'm sorry

**Comment by dfighter1985** [comment]
> I'm sorry

Well, don't be! You haven't done anything wrong.
I just showed you why that one line in the script hasn't been working for ages.

**Pull request merged**
