### PR TITLE
Register 'Deathguard Abraham' to BrillGossip script.

### PR DESCRIPTION
**Pull request by cressidagp**
arcemu: 4155c44e452f58c22164fc3d397734d49188b71f

### CODE REVIEW

**Comment by dfighter1985** [comment]
@cressidagp 
I cannot confirm that he should have gossip.
I tried to look him up on wowhead, wowpedia, even youtube videos but found no traces of gossip.
What was your source?

**Comment by cressidagp** [comment]
Hi there @dfighter1985, i don't have a source   for this one. Found it while played around and then i think why the others deathguard have gossip and this one no? So it was more a logic way of think. But yes of course i could be wrong 🙂

**Comment by cressidagp** [comment]
Btw i didn't dissapear.
Just got new hardware and i'm struggling to make it work 🤣

**Comment by dfighter1985** [comment]
> Hi there @dfighter1985, i don't have a source for this one. Found it while played around and then i think why the others deathguard have gossip and this one no? So it was more a logic way of think. But yes of course i could be wrong 🙂

Well not each and every guard has gossip in World of Warcraft, so I guess he's just one of the less friendly ones who won't just chit-chat with the player.

While I am not for being strictly blizzlike, I have no problems with workaround for features that we cannot yet implement, I also think we should remain as blizzlike as possible.
So I am thankful for this pull request, but I am going to decline it.

> Btw i didn't dissapear. Just got new hardware and i'm struggling to make it work 🤣

It's good to know you are OK! :)
I hope you can get it to work soon.
New year, new hardware! :)

**Pull request closed without merging**
