### PR TITLE
Port ArcEmu to ARM

### PR DESCRIPTION
**Pull request by Artox**
I am working on getting arcemu built and running on a beaglebone black currently. The work should also be applicable to other boards like the raspberrypi and possibly some older armv4 devices(who would want to do that, really?). AARCH64 architecture is not covered though.

### CODE REVIEW

**Comment by RAlexis** [comment]
Well, it took you a little bit.

**Comment by RAlexis** [comment]
Welp. You clearly took your time on this project.

**Comment by dfighter1985** [comment]
I'm glad to see someone still working on all this :)

**Comment by dfighter1985** [comment]
I plan on buying an rpi4 in a few months to play around with it, I might update your PR then and try to build Arcemu with it.

**Comment by dfighter1985** [comment]
@Artox 
Well I had some change of plans I bought RISC V boards instead, and made Arcemu work on that first. Today I tried the output on the device that arrived first.
See https://github.com/arcemu/arcemu/discussions/451

If you are still into these SBC devices you should check them out! They are fun!

Nevertheless Arm is the next target. While I don't have an ARM physical device (yet) I'm going to do as I did with RISC V: first build on qemu then try on device(s).
While Arcemu has diverged a lot since you put in your patch it will still be very helpful!

**Comment by dfighter1985** [comment]
@Artox  
Fresh out of the oven aarch64 support altough only on Linux qemu emulation for now. Going to have to set up a Windows ARM emulated environment too.

**Review by dfighter1985 — COMMENTED** [review]
I had to read up on this, because I'm not that familiar with the internals of the compiler. However according to the docs I read (msdn for example) x86 and amd64 also have alignment requirements for optimal performance.
I'm pretty sure that they were intentionally not respected here to save RAM.
So I'm not going to change packing in Arcemu for now.

**Comment by dfighter1985** [comment]
I have managed to set up a Windows 10 for ARM64 vm in QEMU, with CMake 3.24.4 (first version that runs on ARM), and MinGW for ARM so that I can check out how CMake detects the platform.





It seems it detects it correctly as ARM64.



Obviously these are newer software than what you had @Artox  , but I suspects the System processor was reported incorrectly because of cross-compiling.

Btw this is painfully slow really, so I'm going to continue inestigating the Windows part after I get a hold of an RPI.
I can install this Windows 10 for ARM onto that :)

**Comment by dfighter1985** [comment]
Arcemu now builds, starts up on Windows 10 for ARM64, in a QEMU emulated system at least, and you can also get ingame:



The problem that remains is that the Python Engine crashes on startup. That will still have to be adressed, but either way it works mostly.

Again thanks a lot @Artox , your patch was immensely useful.

**Comment by Artox** [comment]
> I had to read up on this, because I'm not that familiar with the internals of the compiler. However according to the docs I read (msdn for example) x86 and amd64 also have alignment requirements for optimal performance.
> I'm pretty sure that they were intentionally not respected here to save RAM.
> So I'm not going to change packing in Arcemu for now.

If my memory serves me right, what I had seen was a load word instructions on unaligned address, on a real 32-bit arm platform (not emulated). I am still not sure whether or not I had triggered a compiler bug.
The compiler could have generated special code for loading memory at unaligned address, but did not.
Whether this is still true today with newer versions of gcc I do not know.

X86 is known do the right thing quietly. Instead of crash you get performance penalty on unaligned access.

**Comment by Artox** [comment]
> Btw this is painfully slow really, so I'm going to continue investigating the Windows part after I get a hold of an RPI. I can install this Windows 10 for ARM onto that :)

I had installed windows on a macchiatobin board and used remote desktop connection.
It too was slow, because unfortunately Qualcomm is the only vendor blessed by Microsoft, to run Windows on their SoCs. 
PI will be slow too, but at least better than emulation.

**Comment by Artox** [comment]
> Again thanks a lot @Artox , your patch was immensely useful.

You're welcome - and it looks like you were making good progress!

**Comment by dfighter1985** [comment]
> > Again thanks a lot @Artox , your patch was immensely useful.
> 
> You're welcome - and it looks like you were making good progress!

Yes, with cross-compiling. I will try native building again once I get the RPI in January, because sadly the RPI stores here are closed until the 4th.

Even this way it was very very slow because of the stupid Windows GUI.
Opening command prompt = 3 minutes on a Ryzen 2600... I couldn't even install the VS 2017 redistributable libs because the installer would freeze, so I had to bundle them with Arcemu binaries hehe.

**Comment by dfighter1985** [comment]
Got my RPI 4b 2 weeks ago and today finally I got to install Win10 for ARM on my RPI4.
So soon we're going to find out how Arcemu runs on all this :)

**Comment by dfighter1985** [comment]
I could even activate Windows for ARM with a product key I had lying around.
Unfortunately the first update messed up my screen resolution.
However that didn't stop me from trying Arcemu.

@Artox I can happily report that it works not just on an emulated qemu device, but on the real 8 GB Raspberry Pi 4B too.



Altough sadly Windows seems to be so resource intensive that even with the armor case + 2 fans it heats up quite nicely...

IMG_20240118_024234

**Comment by dfighter1985** [comment]
Managed to fix it by placing these two lines in config.txt on the boot partition:

```
hdmi_group=2 
hdmi_mode=2
```

Much more convenient in 1080p :P

**Comment by dfighter1985** [comment]
While I was at it I even tried Windows 11 for Arm 🗡️ 



I think there's plenty of proof now that it works :)

**Pull request closed without merging**
